name: Build Workflow

on:
  repository_dispatch:
    types: [trigger-build-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Display Trigger Payload
      run: |
        echo "Build workflow triggered by: ${{ github.event.client_payload.triggered_by_workflow }}"
        echo "Ref: ${{ github.event.client_payload.ref }}"
        echo "SHA: ${{ github.event.client_payload.sha }}"
        echo "Actor: ${{ github.event.client_payload.actor }}"
